from __future__ import annotations
ASOS_REQUIRED_FIELDS = [
    "uniqueId",
    "productUrl",
    "productName",
]
ASOS_OPTIONAL_FIELDS = [
    "searchUrl",
    "originalPrice",
    "currentPrice",
    "imageUrl",
    "scrapedAt",
]
ASOS_PRODUCT_TYPE_KEYWORDS = {
    "hoodie": ["hoodie"],
    "sweatshirt": ["sweatshirt", "sweater"],
    "t-shirt": ["t-shirt", "tee"],
    "shirt": ["shirt"],
    "shorts": ["shorts"],
    "trousers": ["trousers", "pants"],
    "joggers": ["joggers"],
    "jeans": ["jeans"],
    "dress": ["dress"],
    "skirt": ["skirt"],
    "jacket": ["jacket"],
    "coat": ["coat"],
    "trainers": ["trainers", "sneakers"],
    "shoes": ["shoes"],
    "socks": ["socks"],
    "bag": ["bag"],
    "cap": ["cap", "hat"],
}
ASOS_COLOR_KEYWORDS = [
    "black",
    "white",
    "grey",
    "gray",
    "blue",
    "light blue",
    "navy",
    "green",
    "mid green",
    "pink",
    "light pink",
    "red",
    "burgundy",
    "beige",
    "brown",
    "cream",
    "off white",
    "yellow",
    "orange",
    "purple",
    "silver",
    "gold",
]