from __future__ import annotations
LAMODA_FIELD_ALIASES = {
    "raw_id": ["Артикул", "article", "id", "sku"],
    "seller_article": ["Артикул продавца", "seller_article", "vendor_code"],
    "brand": ["Бренд", "brand", "brandName"],
    "title": ["Название", "title", "name", "productName"],
    "category": ["Категория", "category", "categoryName"],
    "url": ["URL", "url", "productUrl"],
    "price": ["Цена", "price"],
    "old_price": ["Старая цена", "old_price", "oldPrice", "originalPrice"],
    "discount": ["Скидка", "discount", "discountPercent"],
    "currency": ["Валюта", "currency"],
    "color": ["Цвет", "color", "colorName"],
    "sizes": ["Размер", "sizes", "allSizes"],
    "size_names": ["Название размера", "size_names", "sizeNames"],
    "seller": ["Продавец", "seller"],
    "rating": ["Рейтинг", "rating"],
    "reviews": ["Отзывы", "reviews"],
    "questions": ["Вопросы", "questions"],
    "season": ["Сезон", "season"],
    "collection": ["Коллекция", "collection"],
    "quantity": ["Количество", "quantity"],
    "main_image_url": ["Картинка", "image", "imageUrl", "mainImageUrl"],
    "gallery_image_urls": ["Галерея", "gallery", "galleryImages", "images"],
    "description": ["Описание", "description"],
    "composition": ["Состав", "composition", "materials"],
    "country": ["Страна производства", "country", "origin"],
    "availability": ["Наличие", "Статус", "availability", "stockState"],
}
LAMODA_DEFAULT_SOURCE = "lamoda"
LAMODA_DEFAULT_CURRENCY = "RUB"